apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sdk-bot
  labels:
    app: sdk-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sdk-bot
  template:
    metadata:
      labels:
        app: sdk-bot
    spec:
      containers:
      - name: sdk-bot
        image: $DOCKER_REPO
        imagePullPolicy: Always
        ports:
        - name: sdk-bot
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: $OKE_IMAGESECRET