apiVersion: v1
kind: Service
metadata:
  name: sdkbot-service
  labels:
    app: sdkbot
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: ssl-certificate-secret  
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8080
  - name: http
    port: 8081
    targetport: 8080  
  selector:
    app: sdkbot
  type: LoadBalancer
